apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: employee-app
build:
  artifacts:
  - image: employee-service
    context: .
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - k8s/*
