apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-postgres
  labels:
    db: salary-postgres
spec:
  selector:
    matchLabels:
      db: salary-postgres
  template:
    metadata:
      labels:
        db: salary-postgres
    spec:
      containers:
        - name: salary-postgres
          image: postgres:15.3
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: salary-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: salary-postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: salary-postgres-secret
                  key: database

---

apiVersion: v1
kind: Service
metadata:
  name: salary-postgres
  labels:
    db: salary-postgres
spec:
  type: ClusterIP
  selector:
    db: salary-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
