apiVersion: v1
kind: Secret
metadata:
  name: salary-postgres-secret
type: Opaque
stringData:  
  # Database connection details
  host: salary-postgres
  port: "5432"
  database: salary
  username: saeed
  
  # TODO: Replace with a more secure generated password
  # Consider using: kubectl create secret generic salary-postgres-secret --from-literal=password=$(openssl rand -base64 32)
  password: "Salary$3cur3P@ssw0rd2024!"
  
  # R2DBC connection URL for Spring Cloud Bindings
  url: r2dbc:postgresql://salary-postgres:5432/salary
