spring:
  application:
    name: employee-service
  sql:
    init:
      mode: always
server:
  port: 8080
management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,salary
      probes:
        enabled: true
      show-details: always
      show-components: always
salary-service:
  url: "http://localhost:8081"
org:
  springframework:
    cloud:
      bindings:
        boot:
          enable: true
