spring:
  application:
    name: employee-service
  sql:
    init:
      mode: always
server:
  port: 8080
management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,salary
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include:  health, heapdump, info, metrics, prometheus
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

salary-service:
  url: "http://localhost:8081"
