spring:
  application:
    name: employee-service
  sql:
    init:
      mode: always
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
