apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  labels:
    app: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: employee-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 16
            periodSeconds: 5
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://employee-postgres/employee
            - name: SPRING_R2DBC_USERNAME
              value: saeed
            - name: SPRING_R2DBC_PASSWORD
              value: p@ssw0rd

---

apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    app: employee-service
spec:
  type: ClusterIP
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
