apiVersion: v1
kind: Secret
metadata:
  name: employee-postgres-secret
  labels:
    service.binding/type: postgresql
type: Opaque
stringData:
  # Service Binding metadata
  type: postgresql
  provider: postgresql
  
  # Database connection details
  host: employee-postgres
  port: "5432"
  database: employee
  username: saeed
  
  # TODO: Replace with a more secure generated password
  # Consider using: kubectl create secret generic employee-postgres-secret --from-literal=password=$(openssl rand -base64 32)
  password: "Emp1oyee$3cur3P@ssw0rd2024!"
  
  # R2DBC connection URL for Spring Cloud Bindings
  url: r2dbc:postgresql://employee-postgres:5432/employee
