apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-postgres
  labels:
    db: employee-postgres
spec:
  selector:
    matchLabels:
      db: employee-postgres
  template:
    metadata:
      labels:
        db: employee-postgres
    spec:
      containers:
        - name: employee-postgres
          image: postgres:15.3
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: employee-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: employee-postgres-secret
                  key: database

---

apiVersion: v1
kind: Service
metadata:
  name: employee-postgres
  labels:
    db: employee-postgres
    service.binding/type: postgresql
spec:
  type: ClusterIP
  selector:
    db: employee-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
